CREATE TABLE [CUSTRADE]
(

    [UserId] INTEGER  NOT NULL,
    [UserName] NVARCHAR (70),
    [GOODS] NVARCHAR(122),
    [ORDER] NVARCHAR(122) NOT NULL,
    CONSTRAINT [PK_Invoice] PRIMARY KEY  ([UserId]),
    FOREIGN KEY ([UserId]) REFERENCES [UserName] ([UserId]) 
		ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX [IPK_User] ON [CUSTRADE]([UserId]);
